version: "3"
services:
  db:
    build:
      context: ./db/
    volumes:
      - ./db/data:/opt/couchdb/data
    ports:
      - "5984:5984"
  app:
    build:
      context: ./app/
    volumes:
      - ./app/src:/src
    ports:
      - "8000:8000"
